// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.
import SwiftUI

enum SharedTheme {
  static let dark: [String: Color] = [
    "bg-app": Color(.sRGB, red: 0.07450980, green: 0.07450980, blue: 0.08235294, opacity: 1.00000000),
    "bg-sidebar": Color(.sRGB, red: 0.10196078, green: 0.10196078, blue: 0.11372549, opacity: 1.00000000),
    "bg-card": Color(.sRGB, red: 0.11764706, green: 0.11764706, blue: 0.13333333, opacity: 1.00000000),
    "bg-card-hover": Color(.sRGB, red: 0.14509804, green: 0.14509804, blue: 0.16470588, opacity: 1.00000000),
    "bg-elev": Color(.sRGB, red: 0.15686275, green: 0.15686275, blue: 0.17647059, opacity: 1.00000000),
    "bg-input": Color(.sRGB, red: 0.09411765, green: 0.09411765, blue: 0.10588235, opacity: 1.00000000),
    "bg-overlay": Color(.sRGB, red: 0.00000000, green: 0.00000000, blue: 0.00000000, opacity: 0.65000000),
    "border": Color(.sRGB, red: 0.18039216, green: 0.18039216, blue: 0.20000000, opacity: 1.00000000),
    "border-hover": Color(.sRGB, red: 0.22745098, green: 0.22745098, blue: 0.25098039, opacity: 1.00000000),
    "border-focus": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 1.00000000),
    "text-primary": Color(.sRGB, red: 0.94117647, green: 0.94117647, blue: 0.94901961, opacity: 1.00000000),
    "text-secondary": Color(.sRGB, red: 0.69019608, green: 0.69019608, blue: 0.72156863, opacity: 1.00000000),
    "text-muted": Color(.sRGB, red: 0.41568627, green: 0.41568627, blue: 0.44705882, opacity: 1.00000000),
    "accent": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 1.00000000),
    "accent-hover": Color(.sRGB, red: 0.48627451, green: 0.49803922, blue: 1.00000000, opacity: 1.00000000),
    "accent-dim": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.12000000),
    "accent-border": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.35000000),
    "accent-glow": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.20000000),
    "up": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 1.00000000),
    "up-bg": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.12000000),
    "up-border": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.30000000),
    "down": Color(.sRGB, red: 0.97254902, green: 0.44313725, blue: 0.44313725, opacity: 1.00000000),
    "down-bg": Color(.sRGB, red: 0.97254902, green: 0.44313725, blue: 0.44313725, opacity: 0.12000000),
    "down-border": Color(.sRGB, red: 0.97254902, green: 0.44313725, blue: 0.44313725, opacity: 0.30000000),
    "unknown": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 1.00000000),
    "unknown-bg": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.10000000),
    "unknown-border": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.25000000),
    "physical": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 1.00000000),
    "physical-bg": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.10000000),
    "physical-border": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.30000000),
    "virtual": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 1.00000000),
    "virtual-bg": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.10000000),
    "virtual-border": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.30000000),
    "wg-color": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 1.00000000),
    "wg-bg": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.14000000),
    "ovpn-color": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 1.00000000),
    "ovpn-bg": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.14000000),
    "xray-color": Color(.sRGB, red: 0.65490196, green: 0.54509804, blue: 0.98039216, opacity: 1.00000000),
    "xray-bg": Color(.sRGB, red: 0.65490196, green: 0.54509804, blue: 0.98039216, opacity: 0.14000000),
    "none-color": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 1.00000000),
    "none-bg": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.14000000),
  ]
  static let light: [String: Color] = [
    "bg-app": Color(.sRGB, red: 0.98039216, green: 0.98039216, blue: 0.98039216, opacity: 1.00000000),
    "bg-sidebar": Color(.sRGB, red: 0.94901961, green: 0.94901961, blue: 0.96078431, opacity: 1.00000000),
    "bg-card": Color(.sRGB, red: 1.00000000, green: 1.00000000, blue: 1.00000000, opacity: 1.00000000),
    "bg-card-hover": Color(.sRGB, red: 0.96078431, green: 0.96078431, blue: 0.97254902, opacity: 1.00000000),
    "bg-elev": Color(.sRGB, red: 0.94117647, green: 0.94117647, blue: 0.95686275, opacity: 1.00000000),
    "bg-input": Color(.sRGB, red: 1.00000000, green: 1.00000000, blue: 1.00000000, opacity: 1.00000000),
    "bg-overlay": Color(.sRGB, red: 0.00000000, green: 0.00000000, blue: 0.00000000, opacity: 0.35000000),
    "border": Color(.sRGB, red: 0.87058824, green: 0.87058824, blue: 0.89803922, opacity: 1.00000000),
    "border-hover": Color(.sRGB, red: 0.76078431, green: 0.76078431, blue: 0.81176471, opacity: 1.00000000),
    "border-focus": Color(.sRGB, red: 0.32156863, green: 0.35686275, blue: 0.91764706, opacity: 1.00000000),
    "text-primary": Color(.sRGB, red: 0.12549020, green: 0.12549020, blue: 0.14901961, opacity: 1.00000000),
    "text-secondary": Color(.sRGB, red: 0.33725490, green: 0.33725490, blue: 0.38823529, opacity: 1.00000000),
    "text-muted": Color(.sRGB, red: 0.44705882, green: 0.44705882, blue: 0.49803922, opacity: 1.00000000),
    "accent": Color(.sRGB, red: 0.32156863, green: 0.35686275, blue: 0.91764706, opacity: 1.00000000),
    "accent-hover": Color(.sRGB, red: 0.25882353, green: 0.29411765, blue: 0.83529412, opacity: 1.00000000),
    "accent-dim": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.12000000),
    "accent-border": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.35000000),
    "accent-glow": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.20000000),
    "up": Color(.sRGB, red: 0.07058824, green: 0.50980392, blue: 0.35686275, opacity: 1.00000000),
    "up-bg": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.12000000),
    "up-border": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.30000000),
    "down": Color(.sRGB, red: 0.82745098, green: 0.23137255, blue: 0.28627451, opacity: 1.00000000),
    "down-bg": Color(.sRGB, red: 0.97254902, green: 0.44313725, blue: 0.44313725, opacity: 0.12000000),
    "down-border": Color(.sRGB, red: 0.97254902, green: 0.44313725, blue: 0.44313725, opacity: 0.30000000),
    "unknown": Color(.sRGB, red: 0.44705882, green: 0.44705882, blue: 0.49803922, opacity: 1.00000000),
    "unknown-bg": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.10000000),
    "unknown-border": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.25000000),
    "physical": Color(.sRGB, red: 0.32156863, green: 0.35686275, blue: 0.91764706, opacity: 1.00000000),
    "physical-bg": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.10000000),
    "physical-border": Color(.sRGB, red: 0.39215686, green: 0.42352941, blue: 1.00000000, opacity: 0.30000000),
    "virtual": Color(.sRGB, red: 0.65490196, green: 0.38431373, blue: 0.03137255, opacity: 1.00000000),
    "virtual-bg": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.10000000),
    "virtual-border": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.30000000),
    "wg-color": Color(.sRGB, red: 0.07058824, green: 0.50980392, blue: 0.35686275, opacity: 1.00000000),
    "wg-bg": Color(.sRGB, red: 0.20392157, green: 0.82745098, blue: 0.60000000, opacity: 0.14000000),
    "ovpn-color": Color(.sRGB, red: 0.65490196, green: 0.38431373, blue: 0.03137255, opacity: 1.00000000),
    "ovpn-bg": Color(.sRGB, red: 0.96078431, green: 0.61960784, blue: 0.04313725, opacity: 0.14000000),
    "xray-color": Color(.sRGB, red: 0.50196078, green: 0.32156863, blue: 0.75686275, opacity: 1.00000000),
    "xray-bg": Color(.sRGB, red: 0.65490196, green: 0.54509804, blue: 0.98039216, opacity: 0.14000000),
    "none-color": Color(.sRGB, red: 0.44705882, green: 0.44705882, blue: 0.49803922, opacity: 1.00000000),
    "none-bg": Color(.sRGB, red: 0.61176471, green: 0.63921569, blue: 0.68627451, opacity: 0.14000000),
  ]
}
enum DesignMetrics {
  static let railWidth: CGFloat = 64
  static let pageNarrow: CGFloat = 880
  static let contentHorizontal: CGFloat = 28
  static let contentVertical: CGFloat = 21
  static let sectionGap: CGFloat = 21
  static let bodyFont: CGFloat = 14
  static let headingFont: CGFloat = 16.1
  static let lineHeight: CGFloat = 1.55
  static let radiusSmall: CGFloat = 6
  static let radiusMedium: CGFloat = 8
  static let radiusLarge: CGFloat = 12
  static let radiusModal: CGFloat = 16
  static let sp1: CGFloat = 3.5
  static let sp2: CGFloat = 7
  static let sp3: CGFloat = 10.5
  static let sp4: CGFloat = 14
  static let sp5: CGFloat = 17.5
  static let sp6: CGFloat = 21
  static let sp8: CGFloat = 28
}
