// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.
import SwiftUI

enum SharedTheme {
  static let dark: [String: Color] = [
    "bg-app": Color(.sRGB, red: 0.11521716, green: 0.11681875, blue: 0.12911061, opacity: 1.00000000),
    "bg-sidebar": Color(.sRGB, red: 0.14230113, green: 0.14447044, blue: 0.16134469, opacity: 1.00000000),
    "bg-card": Color(.sRGB, red: 0.17209166, green: 0.17485142, blue: 0.19654096, opacity: 1.00000000),
    "bg-card-hover": Color(.sRGB, red: 0.20866860, green: 0.21205827, blue: 0.23887155, opacity: 1.00000000),
    "bg-elev": Color(.sRGB, red: 0.23853932, green: 0.24229349, blue: 0.27197176, opacity: 1.00000000),
    "bg-input": Color(.sRGB, red: 0.13291847, green: 0.13505911, blue: 0.15176836, opacity: 1.00000000),
    "bg-overlay": Color(.sRGB, red: 0.03291643, green: 0.03446199, blue: 0.04861901, opacity: 0.62000000),
    "border": Color(.sRGB, red: 0.25953427, green: 0.26309583, blue: 0.29087978, opacity: 1.00000000),
    "border-hover": Color(.sRGB, red: 0.33265923, green: 0.33699699, blue: 0.37079639, opacity: 1.00000000),
    "border-focus": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 1.00000000),
    "text-primary": Color(.sRGB, red: 0.89102389, green: 0.89417910, blue: 0.91731924, opacity: 1.00000000),
    "text-secondary": Color(.sRGB, red: 0.61000514, green: 0.61695375, blue: 0.67075034, opacity: 1.00000000),
    "text-muted": Color(.sRGB, red: 0.41426382, green: 0.41942333, blue: 0.45955728, opacity: 1.00000000),
    "accent": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 1.00000000),
    "accent-strong": Color(.sRGB, red: 0.38016543, green: 0.38828180, blue: 0.95077972, opacity: 1.00000000),
    "accent-strong-hover": Color(.sRGB, red: 0.45663593, green: 0.48526242, blue: 1.00000000, opacity: 1.00000000),
    "accent-contrast": Color(.sRGB, red: 0.94036848, green: 0.94624114, blue: 0.97523012, opacity: 1.00000000),
    "accent-dim": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 0.14000000),
    "accent-border": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 0.40000000),
    "accent-glow": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 0.28000000),
    "up": Color(.sRGB, red: 0.00000000, green: 0.82074281, blue: 0.56127876, opacity: 1.00000000),
    "up-bg": Color(.sRGB, red: 0.00000000, green: 0.82074281, blue: 0.56127876, opacity: 0.13000000),
    "up-border": Color(.sRGB, red: 0.00000000, green: 0.82074281, blue: 0.56127876, opacity: 0.32000000),
    "down": Color(.sRGB, red: 1.00000000, green: 0.36780036, blue: 0.38967210, opacity: 1.00000000),
    "down-bg": Color(.sRGB, red: 1.00000000, green: 0.36780036, blue: 0.38967210, opacity: 0.13000000),
    "down-border": Color(.sRGB, red: 1.00000000, green: 0.36780036, blue: 0.38967210, opacity: 0.34000000),
    "warn": Color(.sRGB, red: 0.91904654, green: 0.70542133, blue: 0.26556700, opacity: 1.00000000),
    "warn-bg": Color(.sRGB, red: 0.91904654, green: 0.70542133, blue: 0.26556700, opacity: 0.12000000),
    "warn-border": Color(.sRGB, red: 0.91904654, green: 0.70542133, blue: 0.26556700, opacity: 0.32000000),
    "info": Color(.sRGB, red: 0.32130220, green: 0.70887410, blue: 0.95738884, opacity: 1.00000000),
    "info-bg": Color(.sRGB, red: 0.32130220, green: 0.70887410, blue: 0.95738884, opacity: 0.12000000),
    "info-border": Color(.sRGB, red: 0.32130220, green: 0.70887410, blue: 0.95738884, opacity: 0.32000000),
    "unknown": Color(.sRGB, red: 0.56738289, green: 0.57094645, blue: 0.59752545, opacity: 1.00000000),
    "unknown-bg": Color(.sRGB, red: 0.56738289, green: 0.57094645, blue: 0.59752545, opacity: 0.10000000),
    "unknown-border": Color(.sRGB, red: 0.56738289, green: 0.57094645, blue: 0.59752545, opacity: 0.25000000),
    "cat-physical": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 1.00000000),
    "cat-vpn": Color(.sRGB, red: 0.79989764, green: 0.50190368, blue: 0.92822533, opacity: 1.00000000),
    "cat-virtual": Color(.sRGB, red: 0.23189957, green: 0.80428970, blue: 0.86156709, opacity: 1.00000000),
    "cat-system": Color(.sRGB, red: 0.59120438, green: 0.59479926, blue: 0.62158012, opacity: 1.00000000),
    "cat-tunnel": Color(.sRGB, red: 0.97498744, green: 0.58242099, blue: 0.28550187, opacity: 1.00000000),
    "cat-filter": Color(.sRGB, red: 0.94249801, green: 0.44848837, blue: 0.70363154, opacity: 1.00000000),
    "physical": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 1.00000000),
    "physical-bg": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 0.12000000),
    "physical-border": Color(.sRGB, red: 0.55132813, green: 0.59744611, blue: 1.00000000, opacity: 0.32000000),
    "virtual": Color(.sRGB, red: 0.23189957, green: 0.80428970, blue: 0.86156709, opacity: 1.00000000),
    "virtual-bg": Color(.sRGB, red: 0.23189957, green: 0.80428970, blue: 0.86156709, opacity: 0.12000000),
    "virtual-border": Color(.sRGB, red: 0.23189957, green: 0.80428970, blue: 0.86156709, opacity: 0.30000000),
    "wg-color": Color(.sRGB, red: 0.99624662, green: 0.38376175, blue: 0.44088280, opacity: 1.00000000),
    "wg-bg": Color(.sRGB, red: 0.99624662, green: 0.38376175, blue: 0.44088280, opacity: 0.14000000),
    "ovpn-color": Color(.sRGB, red: 0.97498744, green: 0.58242099, blue: 0.28550187, opacity: 1.00000000),
    "ovpn-bg": Color(.sRGB, red: 0.97498744, green: 0.58242099, blue: 0.28550187, opacity: 0.14000000),
    "xray-color": Color(.sRGB, red: 0.79989764, green: 0.50190368, blue: 0.92822533, opacity: 1.00000000),
    "xray-bg": Color(.sRGB, red: 0.79989764, green: 0.50190368, blue: 0.92822533, opacity: 0.14000000),
    "none-color": Color(.sRGB, red: 0.59120438, green: 0.59479926, blue: 0.62158012, opacity: 1.00000000),
    "none-bg": Color(.sRGB, red: 0.59120438, green: 0.59479926, blue: 0.62158012, opacity: 0.14000000),
  ]
  static let light: [String: Color] = [
    "bg-app": Color(.sRGB, red: 0.95058637, green: 0.95299783, blue: 0.97057260, opacity: 1.00000000),
    "bg-sidebar": Color(.sRGB, red: 0.91689953, green: 0.92007339, blue: 0.94333937, opacity: 1.00000000),
    "bg-card": Color(.sRGB, red: 0.98508393, green: 0.98630810, blue: 0.99515943, opacity: 1.00000000),
    "bg-card-hover": Color(.sRGB, red: 0.92988944, green: 0.93307251, blue: 0.95640065, opacity: 1.00000000),
    "bg-elev": Color(.sRGB, red: 0.99883293, green: 0.99965341, blue: 1.00000000, opacity: 1.00000000),
    "bg-input": Color(.sRGB, red: 0.92988944, green: 0.93307251, blue: 0.95640065, opacity: 1.00000000),
    "bg-overlay": Color(.sRGB, red: 0.08232474, green: 0.08469385, blue: 0.10429599, opacity: 0.35000000),
    "border": Color(.sRGB, red: 0.81203359, green: 0.81661823, blue: 0.85070448, opacity: 1.00000000),
    "border-hover": Color(.sRGB, red: 0.68555249, green: 0.69101597, blue: 0.73227381, opacity: 1.00000000),
    "border-focus": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 1.00000000),
    "text-primary": Color(.sRGB, red: 0.11634231, green: 0.11990033, blue: 0.15063540, opacity: 1.00000000),
    "text-secondary": Color(.sRGB, red: 0.32454289, green: 0.33045610, blue: 0.37850532, opacity: 1.00000000),
    "text-muted": Color(.sRGB, red: 0.46999914, green: 0.47592028, blue: 0.52209320, opacity: 1.00000000),
    "accent": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 1.00000000),
    "accent-strong": Color(.sRGB, red: 0.31961947, green: 0.29974472, blue: 0.88968863, opacity: 1.00000000),
    "accent-strong-hover": Color(.sRGB, red: 0.26533935, green: 0.22367316, blue: 0.79741994, opacity: 1.00000000),
    "accent-contrast": Color(.sRGB, red: 0.95342018, green: 0.95930922, blue: 0.98837418, opacity: 1.00000000),
    "accent-dim": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 0.10000000),
    "accent-border": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 0.35000000),
    "accent-glow": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 0.15000000),
    "up": Color(.sRGB, red: 0.00000000, green: 0.63542954, blue: 0.38960643, opacity: 1.00000000),
    "up-bg": Color(.sRGB, red: 0.00000000, green: 0.76915766, blue: 0.51352525, opacity: 0.12000000),
    "up-border": Color(.sRGB, red: 0.00000000, green: 0.63542954, blue: 0.38960643, opacity: 0.32000000),
    "down": Color(.sRGB, red: 0.88781175, green: 0.20303725, blue: 0.22327167, opacity: 1.00000000),
    "down-bg": Color(.sRGB, red: 0.98603195, green: 0.34081695, blue: 0.36640275, opacity: 0.10000000),
    "down-border": Color(.sRGB, red: 0.87191549, green: 0.22763816, blue: 0.27452302, opacity: 0.32000000),
    "warn": Color(.sRGB, red: 0.77852323, green: 0.50932889, blue: 0.00000000, opacity: 1.00000000),
    "warn-bg": Color(.sRGB, red: 0.89288002, green: 0.68029174, blue: 0.23505040, opacity: 0.14000000),
    "warn-border": Color(.sRGB, red: 0.73869041, green: 0.53258453, blue: 0.00000000, opacity: 0.32000000),
    "info": Color(.sRGB, red: 0.01285559, green: 0.47851695, blue: 0.75362129, opacity: 1.00000000),
    "info-bg": Color(.sRGB, red: 0.26592737, green: 0.65867163, blue: 0.90430097, opacity: 0.12000000),
    "info-border": Color(.sRGB, red: 0.00000000, green: 0.48754349, blue: 0.72249844, opacity: 0.32000000),
    "unknown": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 1.00000000),
    "unknown-bg": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 0.08000000),
    "unknown-border": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 0.28000000),
    "cat-physical": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 1.00000000),
    "cat-vpn": Color(.sRGB, red: 0.66450558, green: 0.32963089, blue: 0.80085356, opacity: 1.00000000),
    "cat-virtual": Color(.sRGB, red: 0.00000000, green: 0.62812192, blue: 0.68470698, opacity: 1.00000000),
    "cat-system": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 1.00000000),
    "cat-tunnel": Color(.sRGB, red: 0.82863966, green: 0.42392589, blue: 0.00000000, opacity: 1.00000000),
    "cat-filter": Color(.sRGB, red: 0.80557014, green: 0.26073437, blue: 0.56430849, opacity: 1.00000000),
    "physical": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 1.00000000),
    "physical-bg": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 0.10000000),
    "physical-border": Color(.sRGB, red: 0.36210962, green: 0.37169135, blue: 0.90166080, opacity: 0.32000000),
    "virtual": Color(.sRGB, red: 0.00000000, green: 0.62812192, blue: 0.68470698, opacity: 1.00000000),
    "virtual-bg": Color(.sRGB, red: 0.00000000, green: 0.62812192, blue: 0.68470698, opacity: 0.10000000),
    "virtual-border": Color(.sRGB, red: 0.00000000, green: 0.62812192, blue: 0.68470698, opacity: 0.30000000),
    "wg-color": Color(.sRGB, red: 0.65911564, green: 0.12591188, blue: 0.21627292, opacity: 1.00000000),
    "wg-bg": Color(.sRGB, red: 0.65911564, green: 0.12591188, blue: 0.21627292, opacity: 0.12000000),
    "ovpn-color": Color(.sRGB, red: 0.82863966, green: 0.42392589, blue: 0.00000000, opacity: 1.00000000),
    "ovpn-bg": Color(.sRGB, red: 0.82863966, green: 0.42392589, blue: 0.00000000, opacity: 0.12000000),
    "xray-color": Color(.sRGB, red: 0.66450558, green: 0.32963089, blue: 0.80085356, opacity: 1.00000000),
    "xray-bg": Color(.sRGB, red: 0.66450558, green: 0.32963089, blue: 0.80085356, opacity: 0.12000000),
    "none-color": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 1.00000000),
    "none-bg": Color(.sRGB, red: 0.42743914, green: 0.43142246, blue: 0.46171013, opacity: 0.12000000),
  ]
}
enum DesignMetrics {
  static let railWidth: CGFloat = 64
  static let pageNarrow: CGFloat = 880
  static let contentHorizontal: CGFloat = 28
  static let contentVertical: CGFloat = 21
  static let sectionGap: CGFloat = 21
  static let bodyFont: CGFloat = 14
  static let headingFont: CGFloat = 16.8
  static let lineHeight: CGFloat = 1.55
  static let radiusSmall: CGFloat = 4
  static let radiusMedium: CGFloat = 6
  static let radiusLarge: CGFloat = 9
  static let radiusModal: CGFloat = 10
  static let sp1: CGFloat = 4
  static let sp2: CGFloat = 8
  static let sp3: CGFloat = 12
  static let sp4: CGFloat = 16
  static let sp5: CGFloat = 20
  static let sp6: CGFloat = 24
  static let sp8: CGFloat = 32
}
