#!/usr/bin/env python3
"""Generate both clients' theme values from design/tokens.json. No extra dependencies."""
import argparse
import json
import math
from pathlib import Path
import re
import hashlib

ROOT = Path(__file__).resolve().parent.parent

OKLCH = re.compile(
    r"oklch\(\s*([\d.]+)\s+([\d.]+)\s+([\d.]+)\s*(?:/\s*([\d.]+%?)\s*)?\)")


def _oklch_to_srgb(lightness, chroma, hue):
    """OKLCH -> sRGB (0-1 floats). OKLab->LMS->linear sRGB->gamma."""
    hr = math.radians(hue)
    a_, b_ = chroma * math.cos(hr), chroma * math.sin(hr)
    L = (lightness + 0.3963377774 * a_ + 0.2158037573 * b_) ** 3
    M = (lightness - 0.1055613458 * a_ - 0.0638541728 * b_) ** 3
    S = (lightness - 0.0894841775 * a_ - 1.2914855480 * b_) ** 3
    r = +4.0767416621 * L - 3.3077115913 * M + 0.2309699292 * S
    g = -1.2684380046 * L + 2.6097574011 * M - 0.3413193965 * S
    bl = -0.0041960863 * L - 0.7034186147 * M + 1.7076147010 * S

    def gamma(x):
        x = max(0.0, min(1.0, x))
        return 12.92 * x if x <= 0.0031308 else 1.055 * x ** (1 / 2.4) - 0.055
    return gamma(r), gamma(g), gamma(bl)


def resolve_aliases(theme):
    """Replace `var(--name)` values with the concrete token value."""
    resolved = {}
    for key, value in theme.items():
        seen = set()
        while isinstance(value, str):
            m = re.fullmatch(r"var\(--([a-zA-Z0-9-]+)\)", value.strip())
            if not m or m.group(1) in seen:
                break
            seen.add(m.group(1))
            value = theme.get(m.group(1), value)
        resolved[key] = value
    return resolved


def rgba(value):
    """Parse a CSS color token (hex, rgba(), oklch()) into sRGB floats."""
    m = OKLCH.fullmatch(value.strip())
    if m:
        lightness, chroma, hue = float(m[1]), float(m[2]), float(m[3])
        a = m[4]
        alpha = float(a[:-1]) / 100 if a and a.endswith("%") else float(a or 1)
        return [*_oklch_to_srgb(lightness, chroma, hue), alpha]
    if value.startswith("#"):
        raw = value[1:]
        if len(raw) == 3:
            raw = "".join(c * 2 for c in raw)
        return [int(raw[i:i + 2], 16) / 255 for i in (0, 2, 4)] + [1]
    numbers = [float(v) for v in re.findall(r"[\d.]+", value)]
    return [v / 255 for v in numbers[:3]] + [numbers[3]]


def palette_ts(tokens):
    """src/palette.ts — JS-side colors for canvas/SVG visuals, per theme."""
    pal = tokens["palette"]
    lines = [
        "// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.",
        'import { resolvedAppearance, useTheme } from "./theme";',
        "",
        "export const OWNER_COLORS_DARK = " + json.dumps(pal["dark"]["ownerColors"], indent=2) + ";",
        "export const OWNER_COLORS_LIGHT = " + json.dumps(pal["light"]["ownerColors"], indent=2) + ";",
        "",
        "export function ownerColors(theme: 'dark' | 'light' = resolvedAppearance()): string[] {",
        "  return theme === 'light' ? OWNER_COLORS_LIGHT : OWNER_COLORS_DARK;",
        "}",
        "",
    ]
    for key in ("ownerFallback", "flowNeutral", "flowNeutralFaint", "flowText", "flowTextDim"):
        const_name = re.sub(r"(?<!^)([A-Z])", r"_\1", key).upper()
        lines.append(f"export const {const_name}_DARK = {json.dumps(pal['dark'][key])};")
        lines.append(f"export const {const_name}_LIGHT = {json.dumps(pal['light'][key])};")
        lines.append(f"export function {key[0].lower() + key[1:]}(theme: 'dark' | 'light'): string {{")
        lines.append(f"  return theme === 'light' ? {const_name}_LIGHT : {const_name}_DARK;")
        lines.append("}")
        lines.append("")
    lines += [
        "export function categoricalColor(index: number, theme: 'dark' | 'light' = resolvedAppearance()): string {",
        "  const colors = ownerColors(theme);",
        "  return colors[index % colors.length] ?? ownerFallback(theme);",
        "}",
        "",
        "export function colorForKey(key: string, keys: readonly string[], theme: 'dark' | 'light' = resolvedAppearance()): string {",
        "  const idx = keys.indexOf(key);",
        "  return idx < 0 ? ownerFallback(theme) : categoricalColor(idx, theme);",
        "}",
        "",
        "/** React hook: current resolved theme for canvas/SVG repaints. */",
        "export { resolvedAppearance, useTheme };",
        "",
    ]
    return "\n".join(lines)


def outputs():
    tokens = json.loads((ROOT / "design/tokens.json").read_text())
    assert tokens["dark"].keys() == tokens["light"].keys()
    blocks = {}
    for theme in ("dark", "light"):
        blocks[theme] = "\n".join(f"  --{key}: {value};" for key, value in tokens[theme].items())
    css = ("/* Generated by scripts/generate-ui-theme.py; edit design/tokens.json. */\n"
           ":root, :root[data-theme=dark] {\n" + blocks["dark"] + "\n  color-scheme: dark;\n}\n"
           ":root[data-theme=light] {\n" + blocks["light"] + "\n  color-scheme: light;\n}\n"
           "@media (prefers-color-scheme: light) {\n  :root:not([data-theme=dark]) {\n"
           + blocks["light"] + "\n    color-scheme: light;\n  }\n}\n")
    metric_names = {"railWidth":"rail-w", "pageNarrow":"page-narrow", "bodyFont":"body-font", "radiusSmall":"r-sm", "radiusMedium":"r-md", "radiusLarge":"r-lg", "radiusModal":"r-xl"}
    metric_names.update({f"sp{i}":f"sp-{i}" for i in (1,2,3,4,5,6,8)})
    metrics = "\n".join(f"  --{css_name}: {tokens['metrics'][key]}px;" for key, css_name in metric_names.items())
    css += ":root {\n" + metrics + "\n  --r-full: 999px;\n  --text: var(--text-primary);\n  --text-dim: var(--text-muted);\n  --surface-1: var(--bg-input);\n  --surface-2: var(--bg-elev);\n}\n"
    resolved = {theme: resolve_aliases(tokens[theme]) for theme in ("dark", "light")}
    swift = ["// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.", "import SwiftUI", "", "enum SharedTheme {"]
    for theme in ("dark", "light"):
        swift.append(f"  static let {theme}: [String: Color] = [")
        for key, value in resolved[theme].items():
            r, g, b, a = rgba(value)
            swift.append(f'    "{key}": Color(.sRGB, red: {r:.8f}, green: {g:.8f}, blue: {b:.8f}, opacity: {a:.8f}),')
        swift.append("  ]")
    swift.append("}")
    swift.append("enum DesignMetrics {")
    swift.extend(f"  static let {key}: CGFloat = {value}" for key, value in tokens["metrics"].items())
    swift.append("}")
    return {ROOT / "src/theme.generated.css": css,
            ROOT / "src/palette.ts": palette_ts(tokens),
            ROOT / "macos/Sources/NetworkOrchestrator/Theme.generated.swift": "\n".join(swift) + "\n"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, expected in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f"Stale theme output: {path.relative_to(ROOT)}; run python3 scripts/generate-ui-theme.py")
        else:
            path.write_text(expected)
    if args.check:
        digest = hashlib.sha256((ROOT / "src/icons.tsx").read_bytes()).hexdigest()
        recorded = ROOT / "macos/Sources/NetworkOrchestrator/Resources/Icons/source.sha256"
        if not recorded.exists() or recorded.read_text().strip() != digest:
            raise SystemExit("Native icons are stale; regenerate with scripts/generate-native-icons.py (reportlab).")


if __name__ == "__main__":
    main()
