#!/usr/bin/env python3
"""Generate both clients' theme values from design/tokens.json. No extra dependencies."""
import argparse
import json
from pathlib import Path
import re
import hashlib

ROOT = Path(__file__).resolve().parent.parent


def rgba(value):
    if value.startswith("#"):
        raw = value[1:]
        if len(raw) == 3:
            raw = "".join(c * 2 for c in raw)
        return [int(raw[i:i + 2], 16) / 255 for i in (0, 2, 4)] + [1]
    numbers = [float(v) for v in re.findall(r"[\d.]+", value)]
    return [v / 255 for v in numbers[:3]] + [numbers[3]]


def outputs():
    tokens = json.loads((ROOT / "design/tokens.json").read_text())
    assert tokens["dark"].keys() == tokens["light"].keys()
    blocks = {}
    for theme in ("dark", "light"):
        blocks[theme] = "\n".join(f"  --{key}: {value};" for key, value in tokens[theme].items())
    css = ("/* Generated by scripts/generate-ui-theme.py; edit design/tokens.json. */\n"
           ":root, :root[data-theme=dark] {\n" + blocks["dark"] + "\n  color-scheme: dark;\n}\n"
           ":root[data-theme=light] {\n" + blocks["light"] + "\n  color-scheme: light;\n}\n"
           "@media (prefers-color-scheme: light) {\n  :root:not([data-theme=dark]) {\n"
           + blocks["light"] + "\n    color-scheme: light;\n  }\n}\n")
    metric_names = {"railWidth":"rail-w", "pageNarrow":"page-narrow", "bodyFont":"body-font", "radiusSmall":"r-sm", "radiusMedium":"r-md", "radiusLarge":"r-lg", "radiusModal":"r-xl"}
    metric_names.update({f"sp{i}":f"sp-{i}" for i in (1,2,3,4,5,6,8)})
    metrics = "\n".join(f"  --{css_name}: {tokens['metrics'][key]}px;" for key, css_name in metric_names.items())
    css += ":root {\n" + metrics + "\n  --r-full: 999px;\n  --text: var(--text-primary);\n  --text-dim: var(--text-muted);\n  --surface-1: var(--bg-input);\n  --surface-2: var(--bg-elev);\n}\n"
    swift = ["// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.", "import SwiftUI", "", "enum SharedTheme {"]
    for theme in ("dark", "light"):
        swift.append(f"  static let {theme}: [String: Color] = [")
        for key, value in tokens[theme].items():
            r, g, b, a = rgba(value)
            swift.append(f'    "{key}": Color(.sRGB, red: {r:.8f}, green: {g:.8f}, blue: {b:.8f}, opacity: {a:.8f}),')
        swift.append("  ]")
    swift.append("}")
    swift.append("enum DesignMetrics {")
    swift.extend(f"  static let {key}: CGFloat = {value}" for key, value in tokens["metrics"].items())
    swift.append("}")
    return {ROOT / "src/theme.generated.css": css,
            ROOT / "macos/Sources/NetworkOrchestrator/Theme.generated.swift": "\n".join(swift) + "\n"}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, expected in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != expected:
                raise SystemExit(f"Stale theme output: {path.relative_to(ROOT)}; run python3 scripts/generate-ui-theme.py")
        else:
            path.write_text(expected)
    if args.check:
        digest = hashlib.sha256((ROOT / "src/icons.tsx").read_bytes()).hexdigest()
        recorded = ROOT / "macos/Sources/NetworkOrchestrator/Resources/Icons/source.sha256"
        if not recorded.exists() or recorded.read_text().strip() != digest:
            raise SystemExit("Native icons are stale; regenerate with scripts/generate-native-icons.py (reportlab).")


if __name__ == "__main__":
    main()
