// Generated by scripts/generate-ui-theme.py; edit design/tokens.json.
import { resolvedAppearance, useTheme } from "./theme";

export const OWNER_COLORS_DARK = [
  "oklch(0.72 0.16 277)",
  "oklch(0.76 0.17 162)",
  "oklch(0.76 0.15 55)",
  "oklch(0.70 0.20 22)",
  "oklch(0.72 0.17 315)",
  "oklch(0.78 0.12 205)",
  "oklch(0.80 0.13 120)",
  "oklch(0.74 0.16 350)"
];
export const OWNER_COLORS_LIGHT = [
  "oklch(0.56 0.20 277)",
  "oklch(0.62 0.16 160)",
  "oklch(0.64 0.16 55)",
  "oklch(0.60 0.21 25)",
  "oklch(0.60 0.19 315)",
  "oklch(0.62 0.12 205)",
  "oklch(0.66 0.14 120)",
  "oklch(0.62 0.18 350)"
];

export function ownerColors(theme: 'dark' | 'light' = resolvedAppearance()): string[] {
  return theme === 'light' ? OWNER_COLORS_LIGHT : OWNER_COLORS_DARK;
}

export const OWNER_FALLBACK_DARK = "oklch(0.66 0.01 280)";
export const OWNER_FALLBACK_LIGHT = "oklch(0.55 0.012 280)";
export function ownerFallback(theme: 'dark' | 'light'): string {
  return theme === 'light' ? OWNER_FALLBACK_LIGHT : OWNER_FALLBACK_DARK;
}

export const FLOW_NEUTRAL_DARK = "oklch(0.53 0.016 280)";
export const FLOW_NEUTRAL_LIGHT = "oklch(0.56 0.018 280)";
export function flowNeutral(theme: 'dark' | 'light'): string {
  return theme === 'light' ? FLOW_NEUTRAL_LIGHT : FLOW_NEUTRAL_DARK;
}

export const FLOW_NEUTRAL_FAINT_DARK = "oklch(0.42 0.014 280)";
export const FLOW_NEUTRAL_FAINT_LIGHT = "oklch(0.70 0.015 280)";
export function flowNeutralFaint(theme: 'dark' | 'light'): string {
  return theme === 'light' ? FLOW_NEUTRAL_FAINT_LIGHT : FLOW_NEUTRAL_FAINT_DARK;
}

export const FLOW_TEXT_DARK = "oklch(0.92 0.008 280)";
export const FLOW_TEXT_LIGHT = "oklch(0.24 0.015 280)";
export function flowText(theme: 'dark' | 'light'): string {
  return theme === 'light' ? FLOW_TEXT_LIGHT : FLOW_TEXT_DARK;
}

export const FLOW_TEXT_DIM_DARK = "oklch(0.92 0.008 280 / 0.62)";
export const FLOW_TEXT_DIM_LIGHT = "oklch(0.24 0.015 280 / 0.60)";
export function flowTextDim(theme: 'dark' | 'light'): string {
  return theme === 'light' ? FLOW_TEXT_DIM_LIGHT : FLOW_TEXT_DIM_DARK;
}

export function categoricalColor(index: number, theme: 'dark' | 'light' = resolvedAppearance()): string {
  const colors = ownerColors(theme);
  return colors[index % colors.length] ?? ownerFallback(theme);
}

export function colorForKey(key: string, keys: readonly string[], theme: 'dark' | 'light' = resolvedAppearance()): string {
  const idx = keys.indexOf(key);
  return idx < 0 ? ownerFallback(theme) : categoricalColor(idx, theme);
}

/** React hook: current resolved theme for canvas/SVG repaints. */
export { resolvedAppearance, useTheme };
